#!/bin/bash
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

if [ $# -lt 1 ]
  then
    echo -e "${RED}Error! Too few arguments supplied!${STD}"
    echo -e "${STD}Command: commit <message>"
    exit 1
fi

REPOS="base backup data nginx postgresql odoo soffice upgrade"
for REPO in $REPOS
  do
    echo -e "${YELLOW}Committing docker-odoo-${REPO} repository...${STD}"
    cd /jamoshared/docker-images/docker-odoo-${REPO} && git add --all && git commit -am "$1"
    echo -e "${GREEN}Repository commited${STD}"
    echo -e "${YELLOW}Pushing docker-odoo-${REPO} repository...${STD}"
    cd /jamoshared/docker-images/docker-odoo-${REPO} && git push
    echo -e "${GREEN}Repository pushed${STD}"
done
