#!/bin/bash
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

if [ $# -lt 0 ]
  then
    echo -e "${RED}Error! Too few arguments supplied!${STD}"
    echo -e "${STD}Command: docker-remove-dev <customer> <dbcontainer> <nginxcontainer>"
    exit 1
fi

if [ ! -d /jamoshared/docker-images ]
  then
    echo -e "${YELLOW}Base directory /jamoshared/docker-images not found, creating it...${STD}"
    mkdir -p /jamoshared/docker-images
    echo -e "${GREEN}Directory created"
fi

REPOS="base backup data nginx postgresql odoo soffice upgrade"
for REPO in $REPOS
  do
    if [ ! -d /jamoshared/docker-images/docker-odoo-${REPO} ]
      then 
        echo -e "${YELLOW}Cloning docker-odoo-${REPO} repository...${STD}"
        cd /jamoshared/docker-images && git clone https://github.com/jamotion/docker-odoo-${REPO}.git
        echo -e "${GREEN}Repository sucessfully cloned${STD}"
    fi
    if [ -f /jamoshared/docker-images/docker-odoo-${REPO}/install-scripts ]
      then
        echo -e "${YELLOW}-> Installing scripts of docker-odoo-${REPO} repository...${STD}"
        cd /jamoshared/docker-images/docker-odoo-${REPO} && ./install-scripts
        echo -e "${GREEN}Scripts installed${STD}"
    fi
done

if [ ! -f /usr/local/bin/docker-enter ]
  then
    echo -e "${YELLOW}Installing docker-enter scripts...${STD}"
    docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
    echo -e "${GREEN}docker-enter sucessfully installed${STD}"
fi
